### PR TITLE
Identify Librem Key, behaving like Nitrokey Pro device

### LINKED ISSUE #162: Doesn't detect Librem Key on Ubuntu 18.04
- Application version: `1.4.0snap4` (installed via snap)
- Operating system: `Linux cat 5.0.0-25-generic Nitrokey/nitrokey-app#26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Device model and firmware version: Librem Key, unknown firmware version
- Connected USB port type:2.0
- Issue occurrency: always

### Expected behaviour

The Nitrokey app detects the Librem Key as a regular Nitrokey. This is expected due to PureOS forum posts talking about using the Nitrokey app with the Librem Key.

### Current behaviour

The Nitrokey app does not detect the Librem Key. This seems to be at least in part due to different USB vendor and product IDs (The Librem Key uses `316d:4c4b`).

### Steps for reproduction

Start Nitrokey app with Librem Key inserted.

#### Preconditions

N/A

#### Steps

1. Start Nitrokey app with Librem Key inserted.

### Logs

No relevant logs

### PR DESCRIPTION
**Pull request by AmitAronovitch**
resolves #162

### CODE REVIEW

**Comment by AmitAronovitch** [comment]
Note that the CI tests fail on master as well - I think this is unrelated to the PR

**Comment by szszszsz** [comment]
Hi @AmitAronovitch !

Thank you for the PR! Looks good!
Will run the full tests locally with two other devices, fix the CI to confirm (some unrelated issue indeed), and then merge.

**Comment by szszszsz** [comment]
Merged with changes, as suggested in:
- https://github.com/Nitrokey/libnitrokey/issues/162#issuecomment-635129620
- https://salsa.debian.org/kitterman/libnitrokey/-/merge_requests/3#note_168703

No symbols deleted to keep the binary compatibility.

**Comment by worldofgeese** [comment]
Is there a timeline for a new release of the Nitrokey App that rolls in these and other changes?

**Comment by allnamesaretakeningithub** [comment]
Yes I would be interested about knowing the timeline, if it is public.

**Comment by szszszsz** [comment]
Hi!
There is no specific timeline yet, but I estimate it will take a month since work starts, probably next week. There should be a couple of beta releases, with AppImage and Snap builds to use outside of the regular OS release/update cycle.

**Comment by allnamesaretakeningithub** [comment]
thank you!

**Comment by allnamesaretakeningithub** [comment]
thank you!

**Pull request closed without merging**
