### PR TITLE
Fix device discovery in NitrokeyManager::connect_with_path

### PR DESCRIPTION
**Pull request by d-e-s-o**
The device discovery in NitrokeyManager's connect_with_path method is
broken. It tries to statically determine the vendor ID by using the
first working HID pointer. That's obviously not working when a both a
Nitrokey device and Librem Key are connected and the path is describing
a Librem Key. In such a case the vendor ID used would be that for the
Nitrokey and we would not be able to find the Librem Key at all. This
change fixes up the logic.

### CODE REVIEW

**Comment by d-e-s-o** [comment]
Can this pull request please be merged? @szszszsz

**Comment by szszszsz** [comment]
Noted! Sorry for the delay. Scheduled early for the next week.

**Comment by szszszsz** [comment]
Merged, thank you!

**Comment by d-e-s-o** [comment]
Will you cut a new release with this fix? Without it, it's not possible to test for the Librem Key without manual labor in the form of physically replugging hardware keys.

**Comment by szszszsz** [comment]
Yes, should be done this week (delayed from the previous one).

**Pull request merged**
