### PR TITLE
add meson buildsystem definitions

### PR DESCRIPTION
**Pull request by ignatenkobrain**
References: https://github.com/Nitrokey/nitrokey-app/issues/306
Signed-off-by: Igor Gnatenko <ignatenkobrain@fedoraproject.org>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
* `catch` detection is kinda hacky
* No support for windows/macos (in terms of deps / flags)

Everything else should be on the same feature level as cmake. (all sanitizers are handled by meson, same for -Werror thingy).

**Comment by szszszsz** [comment]
Hi! Thank you for the effort!
I have not tested this yet - could it wait few more days? If you need it for the packaging then let me know.

**Comment by ignatenkobrain** [comment]
@szszszsz since I didn't even start porting nitrokey-app, this definitely can wait ;)

**Comment by ignatenkobrain** [comment]
@szszszsz any news here?

**Comment by szszszsz** [comment]
Merged! Sorry it took so long.
I have not tested this thoroughly yet, but it seems to be quite a nice tool (and fast).
Tests compilation with bundled Catch is not working yet. I hope to look into it in future.

**Pull request closed without merging**
