### PR TITLE
Code cleanups

### PR DESCRIPTION
**Pull request by SoapGentoo**
@szszszsz I'm trying to update libnitrokey for Catch2 v3. As part of that update, Catch2 has enabled a bunch of extra warnings, and this PR is to first clean up the warnings before I move to v3 of Catch.

### CODE REVIEW

**Comment by szszszsz** [comment]
Hey! This looks good, thank you for the fixes! Can you tell what GCC version / C++ did you used? (assuming the latest)
The Catch library is needed only for the tests / development, hence it's packaging can be entirely avoided for the general use case, but updates are always welcome.

**Review by szszszsz — APPROVED** [review]

**Comment by SoapGentoo** [comment]
@szszszsz I'm on GCC 11.3 right now, but will be switching to GCC 12 soon.

While I agree that Catch isn't required at runtime, remember that we actually run the libnitrokey testsuite when we build it, in order to test that everything is fine. This currently means we need to require a version `<3.0` of Catch2, which becomes mroe painful with time, since we will have packages with support for v3 and above.

**Comment by SoapGentoo** [comment]
with regards to `noexcept`: This is a C++11 feature, and while I haven't tested it now, I recall using it with GCC 4.8 7 years ago, and even back then it worked with GCC 4.8 (i.e. CentOS 7), so that should be pretty safe.

**Comment by SoapGentoo** [comment]
@szszszsz any chance of getting this merged?

**Comment by szszszsz** [comment]
Certainly! Sorry for the delay!
Do you need a proper release with this patch?

**Pull request closed without merging**
