### PR TITLE
Few meson fixes and improvements

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@szszszsz would you like to drop cmake/qt stuff and just go with meson or...?  I'm just not sure how to get CI for both :P 

Also if this is the direction, I can port nitrokey-app to meson and then it should be working quite well.

**Comment by szszszsz** [comment]
That easy :-) Just adding the flag in one of the matrix entries, and then in script section recognize the flag and execute proper behavior, similarly to current Qt/CMake selector on [Nitrokey App](https://github.com/Nitrokey/nitrokey-app/blob/master/.travis.yml#L31). Instructions could be in a separate script for easier testing / local build automation as well (on my todo list).
Regarding the builders, I use currently Qt for making final builds for AppImage/macOS/Windows, and CMake for the development, as it is supported natively by the IDE's. I do not know how the latter looks like for Mesos yet, so for now let's settle for an 'extra builder' status for it. 
From brief look I like its features, so it could find easily its place in advanced testing, e.g. when building with sanitizers (in CMake I have to add it by hand).

**Comment by szszszsz** [comment]
If Meson allows easier work for you, e.g. in packagement or other system integration, I would happily merge it to both projects and maintain up to my skills (I know only its basics).

**Comment by ignatenkobrain** [comment]
cc @nirbheek @jpakkane

**Pull request merged**
