### PR TITLE
test3.cc: fix syntax error

### PR DESCRIPTION
**Pull request by ignatenkobrain**
```cxx
In file included from /usr/include/catch/catch.hpp:34:0,
                 from /home/brain/rpmbuild/BUILD/libnitrokey-7f7cfeb45b579204e0bc94bea37e2c810d2e5ec9/unittest/test3.cc:7:
/home/brain/rpmbuild/BUILD/libnitrokey-7f7cfeb45b579204e0bc94bea37e2c810d2e5ec9/unittest/test3.cc: In function 'void ____C_A_T_C_H____T_E_S_T____4()':
/home/brain/rpmbuild/BUILD/libnitrokey-7f7cfeb45b579204e0bc94bea37e2c810d2e5ec9/unittest/test3.cc:116:60: error: expected ')' before ';' token
       WriteGeneralConfig::CommandTransaction::run(stick, p);
                                                            ^
/home/brain/rpmbuild/BUILD/libnitrokey-7f7cfeb45b579204e0bc94bea37e2c810d2e5ec9/unittest/test3.cc:115:3: error: expected primary-expression before ')' token
   REQUIRE_THROWS(
   ^
/home/brain/rpmbuild/BUILD/libnitrokey-7f7cfeb45b579204e0bc94bea37e2c810d2e5ec9/unittest/test3.cc: In function 'void ____C_A_T_C_H____T_E_S_T____6()':
/home/brain/rpmbuild/BUILD/libnitrokey-7f7cfeb45b579204e0bc94bea37e2c810d2e5ec9/unittest/test3.cc:157:50: error: expected ')' before ';' token
       GetHOTP::CommandTransaction::run(stick, p3);
                                                  ^
/home/brain/rpmbuild/BUILD/libnitrokey-7f7cfeb45b579204e0bc94bea37e2c810d2e5ec9/unittest/test3.cc:156:3: error: expected primary-expression before ')' token
   REQUIRE_THROWS(
   ^
/home/brain/rpmbuild/BUILD/libnitrokey-7f7cfeb45b579204e0bc94bea37e2c810d2e5ec9/unittest/test3.cc: In function 'void ____C_A_T_C_H____T_E_S_T____10()':
/home/brain/rpmbuild/BUILD/libnitrokey-7f7cfeb45b579204e0bc94bea37e2c810d2e5ec9/unittest/test3.cc:208:58: error: expected ')' before ';' token
       GetTOTP::CommandTransaction::run(stick, p_get_totp);
                                                          ^
/home/brain/rpmbuild/BUILD/libnitrokey-7f7cfeb45b579204e0bc94bea37e2c810d2e5ec9/unittest/test3.cc:207:3: error: expected primary-expression before ')' token
   REQUIRE_THROWS(
   ^
```

Signed-off-by: Igor Gnatenko <ignatenkobrain@fedoraproject.org>

### CODE REVIEW

**Comment by szszszsz** [comment]
Hi! Thank you for the PR. I have not encountered that earlier. What compiler do you use?

**Comment by ignatenkobrain** [comment]
@szszszsz 

```
[brain@ignatenko-w541 libnitrokey]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.2.1 20170829 (Red Hat 7.2.1-1) (GCC) 
```

**Comment by szszszsz** [comment]
I see. Indeed there is no GCC 7.x in CI tests. Thank you!

**Comment by ignatenkobrain** [comment]
@szszszsz btw, I use system-wide `Catch`... which has version 1.10.0

**Comment by szszszsz** [comment]
And that might be another reason - libnitrokey is bundled with Catch 1.3.5 (there was no need for upgrade since then) but it does not mean tests could be out of spec.

**Pull request closed without merging**
